version : "3.9"
services:
  systemd-builder:
    build:
      dockerfile: Systemd-Builder.Dockerfile
    volumes:
      - ./build:/mount/
  ubuntu-units-builder:
      build:
        dockerfile: Ubuntu-Units.Dockerfile
      volumes:
        - ./build:/mount/